export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const NEW_REFRESH_TOKEN = "NEW_REFRESH_TOKEN";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
export const SET_REDIRECT = "SET_REDIRECT";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const ACCESS_TOKEN_REQUEST = "ACCESS_TOKEN_REQUEST";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const ACCESS_TOKEN_FAIL = "ACCESS_TOKEN_FAIL";

export const GET_DISCOUNT_REQUEST = "GET_DISCOUNT_REQUEST";
export const GET_DISCOUNT_SUCCESS = "GET_DISCOUNT_SUCCESS";
export const GET_DISCOUNT_FAIL = "GET_DISCOUNT_FAIL";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCTS_CLEAN = "GET_PRODUCTS_CLEAN";
export const GET_FILTERED_PRODUCTS_BY_BRAND_REQUEST =
  "GET_FILTERED_PRODUCTS_BY_BRAND_REQUEST";
export const GET_FILTERED_PRODUCTS_BY_BRAND_SUCCESS =
  "GET_FILTERED_PRODUCTS_BY_BRAND_SUCCESS";
export const GET_FILTERED_PRODUCTS_BY_BRAND_FAIL =
  "GET_FILTERED_PRODUCTS_BY_BRAND_FAIL";


export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"; 
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"; 
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"; 
export const GET_PRODUCT_CLEAN = "GET_PRODUCT_CLEAN"; 

export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";
export const GET_COMMENTS_CLEAN = "GET_COMMENTS_CLEAN";

export const SAVE_CARTITEMS_REQUEST = "SAVE_CARTITEMS_REQUEST"; 
export const SAVE_CARTITEMS_SUCCESS = "SAVE_CARTITEMS_SUCCESS"; 
export const SAVE_CARTITEMS_FAIL = "SAVE_CARTITEMS_FAIL"; 


export const GET_SHIPPING_INFO_REQUESR = "GET_SHIPPING_INFO_REQUESR";
export const GET_SHIPPING_INFO_SUCCESS = "GET_SHIPPING_INFO_SUCCESS";
export const GET_SHIPPING_INFO_FAIL = "GET_SHIPPING_INFO_FAIL";
export const CLEAR_SHIPPING_INFO = "CLEAR_SHIPPING_INFO";


